com.webos.app.minimal: use destsuffix for npmsw://
see:
https://lists.openembedded.org/g/openembedded-architecture/message/2007

Now the node_modules end in UNPACKDIR while node in do_install in this
case (or npm.bbclass in general) expects it in ${S}/node_modules.

Fixes:
| DEBUG: Executing shell function do_install
| node:internal/modules/cjs/loader:1252
|   throw err;
|   ^
|
| Error: Cannot find module '/OE/build/oe-core/tmp/work/core2-64-oe-linux/com.webos.app.minimal/1.0/git/node_modules/webpack-cli/bin/cli.js'
|     at Function._resolveFilename (node:internal/modules/cjs/loader:1249:15)
|     at Function._load (node:internal/modules/cjs/loader:1075:27)
|     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
|     at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
|     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
|     at node:internal/main/run_main_module:36:49 {
|   code: 'MODULE_NOT_FOUND',
|   requireStack: []
| }
|
| Node.js v22.12.0
| WARNING: /OE/build/oe-core/tmp/work/core2-64-oe-linux/com.webos.app.minimal/1.0/temp/run.do_install.3293500:145 exit 1 from '/OE/build/oe-core/tmp/work/core2-64-oe-linux/com.webos.app.minimal/1.0/recipe-sysroot-native/usr/bin/node node_modules/webpack-cli/bin/cli.js -o /OE/build/oe-core/tmp/work/core2-64-oe-linux/com.webos.app.minimal/1.0/image/test'

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>