WIP: snapper: pass libdir to fix installed-vs-shipped with multilib
* otherwise it defaults to [EPREFIX/lib] which doesn't work when libdir
  is configured to something else (e.g. lib32 with multilib) causing:

ERROR: lib32-snapper-0.11.2-r0 do_package: QA Issue: lib32-snapper: Files/directories were installed but not shipped in any package:
  /usr/lib/systemd
  /usr/lib/systemd/system
  /usr/lib/systemd/system/snapper-timeline.timer
  /usr/lib/systemd/system/snapper-timeline.service
  /usr/lib/systemd/system/snapper-boot.timer
  /usr/lib/systemd/system/snapper-cleanup.timer
  /usr/lib/systemd/system/snapperd.service
  /usr/lib/systemd/system/snapper-boot.service
  /usr/lib/systemd/system/snapper-cleanup.service
  /usr/lib/snapper/systemd-helper
  /usr/lib/snapper/installation-helper
  /usr/lib/snapper/plugins
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
lib32-snapper: 12 installed and not shipped files. [installed-vs-shipped]

* WIP because wasn't tested in runtime at all

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>